name: Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      target:
        description: Publishing target
        type: choice
        options: [pypi, testpypi]
        default: testpypi

jobs:
  publish:
    uses: AshMatics/ashmatics-workflows/.github/workflows/publish-pypi.yml@v1
    with:
      python-version: "3.11"
      target: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'pypi' }}
